### PR TITLE
[ci] Restore MPI jobs on macOS

### PR DESCRIPTION
**Pull request by StrikerRUS**
Linking #6425.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Hey great! I've restarted the one failed Azure DevOps job (it isn't an MPI job, just timed out for what looks like temporary Azure issues).

By the way, I went searching for why this might now work. This looks relevant: https://gitlab.kitware.com/cmake/cmake/-/issues/25942

In #6425, @borchero mentioned that these jobs were failing because `CMake` couldn't find MPI on macOS. That CMake conversation suggests that maybe it was a `gcc` bug, fixed in later versions of `gcc`.

**Comment by StrikerRUS** [comment]
> I've restarted the one failed Azure DevOps job

Thank you!

I'm sorry, I can't restart Azure jobs anymore because I get HTTP 401 error everytime when try to sign in lightgbm-ci.visualstudio.com. Maybe it's due to sanctions or I was simply removed from that workspace.

**Comment by jameslamb** [comment]
It does look like you've been removed. I'll ask for you to be re-added over in the maintainer Slack.

**Comment by jameslamb** [comment]
@StrikerRUS do you have an Azure DevOps account using the email address your commits are signed with? If not and you want to use a different email address, could you contact me at one of the communication methods linked on my GitHub profile and let me know the email you use for Azure DevOps?

**Comment by jameslamb** [comment]
Thanks @StrikerRUS ! I captured that email address and sent it to @shiyu1994 in the maintainer Slack. Deleted your comment here so that address won't be on GitHub (even in image form).

**Comment by StrikerRUS** [comment]
@jameslamb Thank you very much for your help! 🤗

**Comment by jameslamb** [comment]
Of course! Happy to have you back with us 😊

**Comment by shiyu1994** [comment]
@StrikerRUS Could you provide the latest account that you can use to login into Azure DevOps? Thanks.

**Pull request merged**
