### PR TITLE
[ci] [R-package] Add paste_linter

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
## Description 

Added `paste_linter`.

## Lint warnings

```
[1] Total linting issues found: 11
[[1]]
/home/atis/Projects/LightGBM/build_r.R:73:7: warning: [paste] toString(.) is more expressive than paste(., collapse = ", "). Note als$
    , paste0(unrecognized_args, collapse = ", ")
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[2]]
/home/atis/Projects/LightGBM/build_r.R:420:5: warning: [paste] toString(.) is more expressive than paste(., collapse = ", "). Note al$
  , paste0(c_api_symbols, collapse = ", ")
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[3]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Booster.R:827:9: warning: [paste] toString(.) is more expressive than paste(., collapse $
      , paste(names(additional_params), collapse = ", ")
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[4]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Booster.R:1134:9: warning: [paste] toString(.) is more expressive than paste(., collapse$
      , paste(data_names, collapse = ", ")
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[5]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Booster.R:1148:9: warning: [paste] toString(.) is more expressive than paste(., collapse$
      , paste(eval_names, collapse = ", ")
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[6]]
/home/atis/Projects/LightGBM/R-package/R/lgb.convert_with_rules.R:23:30: warning: [paste] toString(.) is more expressive than paste(.$
        col_detail_string <- paste0(
                             ^~~~~~~

[[7]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Dataset.R:474:13: warning: [paste] toString(.) is more expressive than paste(., collapse$
          , paste0(sQuote(.INFO_KEYS()), collapse = ", ")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[8]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Dataset.R:526:13: warning: [paste] toString(.) is more expressive than paste(., collapse$
          , paste0(sQuote(.INFO_KEYS()), collapse = ", ")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[9]]
/home/atis/Projects/LightGBM/R-package/R/lgb.Predictor.R:227:26: warning: [paste] toString(.) is more expressive than paste(., collap$
                       , paste(class(data)
                         ^~~~~~~~~~~~~~~~~

[[10]]
/home/atis/Projects/LightGBM/R-package/tests/testthat/test_Predictor.R:440:21: warning: [paste] paste0(...) is better than paste(...,$
    row.names(X) <- paste("rname", seq(1L, nrow(X)), sep = "")
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[11]]
/home/atis/Projects/LightGBM/R-package/tests/testthat/test_Predictor.R:455:21: warning: [paste] paste0(...) is better than paste(...,$
    row.names(X) <- paste("rname", seq(1L, nrow(X)), sep = "")
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Suggested change example

``` r
> a <- list("abc", "def")
> paste0("Unrecognized arguments: ", paste0(a, collapse = ", "))
[1] "Unrecognized arguments: abc, def"
> paste0("Unrecognized arguments: ", toString(a))
[1] "Unrecognized arguments: abc, def"
```

### Issue

Contributes to #5303

- [x] `paste_linter()`

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Very nice, thank you so much for your contributions!! I just left one small suggestion.

I've also made a few changes to the title and description:

* removed `(#5303)` from the PR title. Links to the relevant issue should be in the PR description instead.
    - this project uses squash merging, and by default when you do that on GitHub, GitHub will generate a single commit message of the form `{PR title} ({PR number})`
    - so having two numbers, like `({issue}) ({PR})` might be confusing there
    - see https://github.com/microsoft/LightGBM/commits/master
* changed "Closes" language in the description to "Contributes to". After this PR is merged, `string_boundary_linter()` will still be left in #5303

**Comment by jameslamb** [comment]
I don't believe the failing `check-docs` build is related to the changes in this PR.

```text
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
make: *** [Makefile:20: html] Error 2
```

([build log](https://github.com/microsoft/LightGBM/runs/7005796287?check_suite_focus=true))

One of the maintainers here will look into this as soon as possible. Sorry for the inconvenience.

**Comment by jameslamb** [comment]
@CuriousCorrelation in the future, please don't use force-pushing in this project. We use squash merging (all commits get collapsed into one upon merge), and having individual commits on a PR makes it easier for maintainers to understand what changes you made in response to review comments.

**Comment by CuriousCorrelation** [comment]
Ah sorry about that and thanks for letting me know. I will keep that in mind.

**Comment by jameslamb** [comment]
I'm manually re-running the `check-docs` job now that #5322 has been merged. Hopefully that fixes it. Sorry for the inconvenience!

**Comment by CuriousCorrelation** [comment]
Sure no problem. Any particular way I should do that? 
Should I 
1. fetch latest on fork-master -> merge -> pull remote -> checkout branch -> merge master -> push 
2. add new origin 'upstream' -> fetch upstream master -> rebase upstream/master -> force push

**Comment by jameslamb** [comment]
> Any particular way I should do that?

You don't need to force push. From the root of your fork, do the following.

```shell
# set a remote alias for microsoft/LightGBM if you don't already have one
git remote add upstream https://github.com/microsoft/LightGBM.git

# pull the latest upstream changes into your fork's "master" branch
git checkout master
git pull upstream master

# merge "master" into your feature branch, creating a merge commit
git checkout lint/paste_linter
git merge master

# push that merge commit
git push origin lint/paste_linter
```

**Comment by CuriousCorrelation** [comment]
@jameslamb I'd love to! I'll open a PR as soon as I can.

**Pull request merged**
